extends: airbnb
parser: babel-eslint
rules:
  arrow-parens: 0
  consistent-return: 0
  comma-dangle: 0
  curly:
    - 2
    - multi
  func-names: 2
  func-style:
    - 2
    - expression
    - allowArrowFunctions: true
  global-require: 0
  import/extensions: 0
  import/first: 0
  import/no-dynamic-require: 0
  import/no-extraneous-dependencies: 0
  import/no-named-as-default: 0
  import/no-unresolved: 0
  import/prefer-default-export: 0
  indent:
    - 2
    - 4
    - SwitchCase: 1
  jsx-a11y/anchor-is-valid: 0
  max-len:
    - 2
    - code: 100
      tabWidth: 4
  new-cap: 0
  no-implicit-coercion: 2
  no-confusing-arrow: 0
  no-console: 2
  no-plusplus: 0
  no-return-assign: 0
  no-underscore-dangle: 0
  padded-blocks: 0
  semi:
    - 2
    - always
  react/destructuring-assignment: 0
  react/jsx-filename-extension: 0
  react/jsx-indent:
    - 2
    - 4
  react/jsx-indent-props:
    - 2
    - 4
  react/jsx-boolean-value: 0
  react/prefer-stateless-function: 2
  react/no-access-state-in-setstate: 0
  react/no-is-mounted: 2
  react/prefer-es6-class: 2
  react/jsx-curly-spacing:
    - 2
    - always
  react/forbid-prop-types: 0
  react/jsx-handler-names: 2
  react/jsx-key: 2
  react/jsx-no-bind: 2
  react/jsx-no-duplicate-props: 2
  react/jsx-one-expression-per-line: 0
  react/jsx-pascal-case: 2
  react/require-default-props: 0
plugins:
  - react
env:
  browser: true
  node: true
